import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Menu from "@/components/Menu";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className="h-screen flex">
      {/* LEFT */}
      <div className="w-[16%] xl:w-[14%]  p-4 bg-[#17080d]">
        <Link href= "/" className="flex items-center justify-center lg:justify-start gap-2">
          <Image src="/hippo-logo.svg" alt="Logo" width={32} height={32}/>
          <span className="hidden lg:block">HippoDash</span>
        </Link>
        <Menu />
      </div>
      {/* RIGHT */}
      <div className="w-[86%] md:w-[92%] lg:w-[84%] xl:w-[86%] overflow-scroll">
        <Navbar />
        {children}
      </div>
    </div>
      </body>
    </html>
  );
}
